package dtu.dk;

public enum Protocol {
    CONNECT,
    CONNECTED,
    CONNECT_DENIED,
    CONNECT_DUPLICATE_URI,
    CONNECT_PORT_NOT_AVAILABLE,
    CONNECT_ACCEPTED,
    READY,
    PLAYERS,
    WORDS,
    LOADING_DONE,
    START,
    STARTED,
    UPDATE,
    EXTRA_WORD,
    LIFE,
    GET_USERNAME
}
